# Generated by Django 4.1.2 on 2022-11-07 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_like_remove_post_users_liked_alter_post_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='url',
        ),
        migrations.CreateModel(
            name='Ask',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.post')),
                ('title', models.CharField(max_length=200)),
            ],
            bases=('posts.post',),
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.post')),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=200)),
            ],
            bases=('posts.post',),
        ),
    ]
